# Generated by Django 3.0.5 on 2020-04-06 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pathology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_details',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 4, 6, 20, 53, 31, 228141)),
        ),
    ]
